# Per-namespace resource quotas - Application allocation out of total 8 vCPU / 240GB RAM
# The remainder is used by the claudecode-terminal namespace and system (kube-system)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-quota
  namespace: papers-frontend
  labels:
    app.kubernetes.io/part-of: papers-with-claudecode
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 4Gi
    limits.cpu: "2"
    limits.memory: 8Gi
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: papers-backend
  labels:
    app.kubernetes.io/part-of: papers-with-claudecode
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 8Gi
    limits.cpu: "4"
    limits.memory: 16Gi
    pods: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: blockchain-quota
  namespace: papers-blockchain
  labels:
    app.kubernetes.io/part-of: papers-with-claudecode
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 4Gi
    limits.cpu: "2"
    limits.memory: 8Gi
    pods: "10"
