# NetworkPolicy -- minimize network access for sandbox Pods
#
# WARNING: The default k3s CNI (Flannel) does not support NetworkPolicy.
# To enforce these policies, install Calico or Cilium CNI:
#   Reinstall k3s: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-backend=none --disable-network-policy" sh -
#   Install Calico: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml
#
# Applying on Flannel is silently ignored (harmless but has no effect).

# 1. Sandbox Pod -> allow API Proxy + DNS + Kite MCP + web-terminal-service (block other traffic)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sandbox-egress-restrict
  namespace: claudecode-terminal
spec:
  podSelector:
    matchLabels:
      app: claudecode-sandbox
  policyTypes:
    - Egress
  egress:
    # Allow traffic to the API Proxy service
    - to:
        - podSelector:
            matchLabels:
              app: api-proxy
      ports:
        - port: 8080
          protocol: TCP
    # Allow HTTPS egress for Kite MCP server (neo.dev.gokite.ai)
    - ports:
        - port: 443
          protocol: TCP
    # Allow traffic to web-terminal-service (x402 payment API, Service port 80)
    - to:
        - podSelector:
            matchLabels:
              app: web-terminal-service
      ports:
        - port: 80
          protocol: TCP
        - port: 3000
          protocol: TCP
    # Allow DNS lookups (kube-dns / CoreDNS)
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP

---

# 2. API Proxy -> allow external Anthropic API traffic
# The API Proxy Pod needs to communicate with the external internet (api.anthropic.com), so no egress restriction
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-proxy-egress-allow
  namespace: claudecode-terminal
spec:
  podSelector:
    matchLabels:
      app: api-proxy
  policyTypes:
    - Egress
  egress:
    - {}  # Allow all outbound traffic

---

# 3. API Proxy Ingress -- allow only requests from sandbox Pods
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-proxy-ingress-restrict
  namespace: claudecode-terminal
spec:
  podSelector:
    matchLabels:
      app: api-proxy
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: claudecode-sandbox
      ports:
        - port: 8080
          protocol: TCP
