# NetworkPolicy — Minimize network access for sandbox Pods
#
# ⚠️  Note: The default k3s CNI (Flannel) does not support NetworkPolicy.
# To actually enforce these policies, Calico or Cilium CNI installation is required:
#   Reinstall k3s: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-backend=none --disable-network-policy" sh -
#   Install Calico: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml
#
# Applying on Flannel will be silently ignored without errors (harmless but has no effect).

# 1. Sandbox Pod → Allow only API Proxy + DNS (block external communication)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sandbox-egress-restrict
  namespace: claudecode-terminal
spec:
  podSelector:
    matchLabels:
      app: claudecode-sandbox
  policyTypes:
    - Egress
  egress:
    # Allow communication to the API Proxy service
    - to:
        - podSelector:
            matchLabels:
              app: api-proxy
      ports:
        - port: 8080
          protocol: TCP
    # Allow DNS lookups (kube-dns / CoreDNS)
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP

---

# 2. API Proxy → Allow external Anthropic API communication
# API Proxy Pod needs to communicate with the external internet (api.anthropic.com), so no egress restrictions
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-proxy-egress-allow
  namespace: claudecode-terminal
spec:
  podSelector:
    matchLabels:
      app: api-proxy
  policyTypes:
    - Egress
  egress:
    - {}  # Allow all external communication

---

# 3. API Proxy Ingress — Allow only requests coming from sandbox Pods
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-proxy-ingress-restrict
  namespace: claudecode-terminal
spec:
  podSelector:
    matchLabels:
      app: api-proxy
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: claudecode-sandbox
      ports:
        - port: 8080
          protocol: TCP
